name: Playwright Tests with Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-playwright pytest-html allure-pytest  # Ensure required plugins are installed

      - name: Install Playwright
        run: |
          source venv/bin/activate
          pip install playwright
          playwright install --with-deps

      - name: Verify Plugin Installation
        run: |
          source venv/bin/activate
          pip list | grep pytest  # Check installed pytest plugins

      - name: Run Playwright Tests
        run: |
          source venv/bin/activate
          pytest tests/e2e \
            --html=test-results/report.html \
            --self-contained-html \
            --alluredir=test-results/ || true

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-report
          path: test-results/
